server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot_tenant?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: iot_platform
    password: 8a4b041e
logging:
  level:
    com.zlgcloud: DEBUG
### SDK
project.id: iot
megaease:
  output:
    type: console
  trace.enabled: false
  metrics.enabled: false

