server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot_firmware?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: iot_firmware
    password: 8a4b041e
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
logging:
  level:
    com.zlgcloud: DEBUG
### SDK
project.id: iot
megaease:
  output:
    type: console
  trace.enabled: false
  metrics.enabled: false

